SELECT
  REPLACE(ARTNR,'Sam','')ARTNR,
  FLOOR(B.WERT) WERT,
  FLOOR(C.WERT) CZARNY
FROM
  ART A
  LEFT JOIN ARTPREISE B ON A.ARTIKELID = B.ARTIKELID AND B.PREISFELDNR =11
  LEFT JOIN ARTPREISE C ON A.ARTIKELID = C.ARTIKELID AND C.PREISFELDNR =12
  AND B.PREISSCHEMAID in(39)
WHERE
  ARTKLCODE = 6210
  AND PRODUKTTYP <> '99'
  AND ARTNR IN('SamLC','SamLN','SamR','SamRB','SamRPP','SamW')
order by
  1,
  2 FOR json PATH